name: othr_slider
description: "A highly customizable range slider that allows you to control every aspect of the slider's appearance, including track, thumb, overlay, and label configuration."
version: 0.0.2
homepage: https://github.com/OscrTR/OthrSlider

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
